spring:
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/oylong/newblog/mapper/*.xml
  type-aliases-package: com.oylong.newblog.entity
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true






