spring:
  datasource:
    name: myblog
    type: com.alibaba.druid.pool.DruidDataSource
    #druid\u8FDE\u63A5\u6C60\u76F8\u5173\u914D\u7F6E
    druid:
      #\u76D1\u63A7\u62E6\u622A\u7EDF\u8BA1\u7684filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123123
      #\u914D\u7F6E\u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      initial-size: 1
      min-idle: 1
      max-active: 20
      #\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      max-wait: 6000
      #\u95F4\u9694\u591A\u4E45\u68C0\u6D4B\u4E00\u6B21\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5
      time-between-eviction-runs-millis: 60000
      #\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      #\u6253\u5F00PSCache\uFF0C\u5E76\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F\u3002oracle\u8BBE\u7F6E\u4E3Atrue\uFF0Cmysql\u8BBE\u7F6E\u4E3Afalse\u3002\u5206\u5E93\u5206\u8868\u8BBE\u7F6E\u8F83\u591A\u63A8\u8350\u8BBE\u7F6E
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    timeout: 1000

server:
  port: 8088
